FROM golang:1.23-alpine AS build
WORKDIR /src
COPY contracts ./contracts
COPY payment-service ./payment-service
WORKDIR /src/payment-service
RUN go mod download
RUN go build -o /bin/payment-service ./cmd/payment-service

FROM alpine:3.20
WORKDIR /app
COPY --from=build /bin/payment-service /app/payment-service
EXPOSE 8081 50051
CMD ["/app/payment-service"]
